### ISSUE TITLE
error messages with latest streamlink

### ISSUE THREAD

**Issue by johnthecracker** [back-to/generic#21]
Installation file:

streamlink-5.5.1-1-py311-x86_64.zip

Without generic plugin, ther isn't any error. These are errors with generic plugin:

`
C:\>streamlink
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\P\STREAMLINK\bin\streamlink.exe\__main__.py", line 18, in <module>
  File "C:\P\STREAMLINK\pkgs\streamlink_cli\main.py", line 881, in main
    setup_streamlink()
  File "C:\P\STREAMLINK\pkgs\streamlink_cli\main.py", line 709, in setup_streamlink
    streamlink = Streamlink({"user-input-requester": ConsoleUserInputRequester(console)})
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\P\STREAMLINK\pkgs\streamlink\session.py", line 256, in __init__
    self.load_builtin_plugins()
  File "C:\P\STREAMLINK\pkgs\streamlink\session.py", line 622, in load_builtin_plugins
    self.load_plugins(plugins.__path__[0])
  File "C:\P\STREAMLINK\pkgs\streamlink\session.py", line 638, in load_plugins
    mod = load_module(module_name, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\P\STREAMLINK\pkgs\streamlink\utils\module.py", line 14, in load_module
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\P\STREAMLINK\pkgs\streamlink\plugins\generic.py", line 305, in <module>
    type=num(int, min=0, max=25),
         ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: num() got an unexpected keyword argument 'min'
`

![Clipboard Image (08-05-2023 21 19 31)](https://user-images.githubusercontent.com/25414991/236929631-2ac0b3e1-cefc-4016-a75e-77eef4706684.jpg)

**Comment by WolfganP** [comment]
See https://github.com/back-to/generic/issues/20#issuecomment-1510439091
Edit the mentioned line in `generic.py` and you're good to go...

**Comment by johnthecracker** [comment]
Thanks @WolfganP. 
Your fix works. 
I may close this isue now.
